# --- Configuração de Build ---
[build]
  functions = "netlify/functions"

# --- Regras de Cabeçalho de Segurança ---
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # ATUALIZAÇÃO: Política de segurança estável que permite Google Analytics e PostHog
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com https://cdn.jsdelivr.net https://us.i.posthog.com https://us-assets.i.posthog.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' https://res.cloudinary.com data: blob:; connect-src 'self' https://api.cloudinary.com https://www.google-analytics.com https://us.i.posthog.com;"

# --- Regra de Redirecionamento para o Encurtador ---
[[redirects]]
  from = "/s/:slug"
  to = "/.netlify/functions/redirect?slug=:slug"
  status = 200